trigger:
  - master

pool:
  vmImage: 'macOS-10.14'

resources:
  repositories:
  - repository: templates
    type: github
    name: damienaicheh/AzureDevOpsTemplates
    ref: refs/tags/v1.0.0
    endpoint: GitHubTemplates

variables:
  - group: xamarin-full-pipeline
  - template: variables.yml

schedules:
- cron: "0 0 * * 1-5"
  displayName: Daily midnight build
  branches:
    include:
    - master

stages:
  - stage: Run_Unit_Tests
    jobs:
      - job:
        displayName: 'Run Unit Tests'
        steps:
          - template: run_unit_tests.yml@templates
            parameters:
              solutionPath: '$(solutionPath)'
              projects: '$(Build.SourcesDirectory)/XamarinDevOps.Tests/*.csproj'
              buildConfiguration: '$(buildConfiguration)'

  - stage: Build_Xamarin_Android
    dependsOn: Run_Unit_Tests
    jobs:
      - job:
        displayName: 'Build Xamarin.Android'
        workspace:
          clean: all
        steps:
          - template: init_restore.yml@templates
            parameters:
              solutionPath: '$(solutionPath)'

          - template: bump_android_manifest_version.yml@templates
            parameters:
              androidManifestPath: '$(Build.SourcesDirectory)/XamarinDevOps.Android/Properties/AndroidManifest.xml'

          - template: icon_banner.yml@templates
            parameters:
              sourceFolder: '$(Build.SourcesDirectory)/XamarinDevOps.Android/Resources'
              contents: '**/icon.png'
              versionName: '$(buildConfiguration)'

          - template: copy_content_file.yml@templates
            parameters:
              sourceFile: '$(Build.SourcesDirectory)/configurations/config-$(buildConfiguration).json'
              targetFile: '$(Build.SourcesDirectory)/XamarinDevOps.Android/Assets/config.json'
          
          - template: build_xamarin_android.yml@templates
            parameters:
              xamarinSdkVersion: '$(xamarinSdkVersion)'
              packageFormat: 'apk' # Choose apk or aab depending on your needs
              projectFile: '$(Build.SourcesDirectory)/XamarinDevOps.Android/*.csproj'
              buildConfiguration: '$(buildConfiguration)'
              apksignerKeystoreFile: 'production.jks'
              apksignerKeystorePassword: $(keystore.password)
              apksignerKeystoreAlias: $(key.alias)
              apksignerKeyPassword: $(key.password)
          
          - template: publish_artifacts.yml@templates
            parameters:
              sourceFolder: '$(Build.SourcesDirectory)/XamarinDevOps.Android/bin/$(buildConfiguration)'
              contents: '*Signed.apk'
              artifactName: '$(buildConfiguration)_android'

  - stage: Build_Xamarin_iOS
    dependsOn: Run_Unit_Tests
    jobs:
      - job:
        displayName: 'Build Xamarin.iOS'
        workspace:
          clean: all
        steps:
          - template: init_restore.yml@templates
            parameters:
              solutionPath: '$(solutionPath)'

          - template: bump_ios_version.yml@templates
            parameters:
              infoPlistPath: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/Info.plist'

          - template: icon_banner.yml@templates
            parameters:
              sourceFolder: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/Assets.xcassets/AppIcon.appiconset'
              versionName: '$(buildConfiguration)'

          - template: copy_content_file.yml@templates
            parameters:
              sourceFile: '$(Build.SourcesDirectory)/configurations/config-$(buildConfiguration).json'
              targetFile: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/Assets/config.json'

          - template: build_xamarin_ios_ipa.yml@templates
            parameters:
              xamarinSdkVersion: '$(xamarinSdkVersion)'
              p12FileName: '$(p12FileName)'
              p12Password: '$(p12Password)'
              provisioningProfile: '$(provisioningProfile)'
              solutionPath: '$(solutionPath)'
              buildConfiguration: '$(buildConfiguration)'
              signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
              signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

          - template: publish_artifacts.yml@templates
            parameters:
              sourceFolder: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/bin/iPhone/$(buildConfiguration)'
              contents: '*.ipa'
              artifactName: '$(buildConfiguration)_ios'

  - stage: Deploy_Android
    dependsOn: Build_Xamarin_Android
    jobs:
      - job:
        displayName: 'Deploy Xamarin.Android'
        steps:
          - template: deploy_to_app_center.yml@templates
            parameters:
              appSlug: '$(androidAppSlug)'
              fileToPublish: '$(buildConfiguration)_android/*.apk'
              distributionGroupId: '$(androidDistributionGroupId)'

  - stage: Deploy_iOS
    dependsOn: Build_Xamarin_iOS
    jobs:
      - job:
        displayName: 'Deploy Xamarin.iOS'
        steps:
          - template: deploy_to_app_center.yml@templates
            parameters:
              appSlug: '$(iOSAppSlug)'
              fileToPublish: '$(buildConfiguration)_ios/*.ipa'
              distributionGroupId: '$(iOSDistributionGroupId)'